### ISSUE TITLE
Adjust testing evironment

### ISSUE THREAD

**Issue by evalott100** [PandABlocks/PandABlocks-ioc#19]
* Change the dummy server in the thread to be a mocked pandablocks-client that gives canned responses

**Comment by AlexanderWells-diamond** [comment]
This is definitely a good idea, now that this code is no longer embedded in the client code.

One important aspect to consider when making these mocks is how to handle the repeated calls to PandA-client functions. There's two approaches I've used: Having the order of responses fixed, or having them depend upon the exact data requested.

The former is what the current tests do _for the most part_, [as seen here](https://github.com/PandABlocks/PandABlocks-ioc/blob/main/tests/conftest.py#L440C37-L440C37). That list is just iterated through for each subsequent call to the client code.

The second is used in some other tests, [as seen here](https://github.com/PandABlocks/PandABlocks-ioc/blob/main/tests/conftest.py#L498). This looks for a specific request in that list, and returns the associated data if it is found. Otherwise it'll return the next item in the `send` buffer. 

There's advantages and disadvantages to each approach. I'd lean towards developing a mechanism more like the latter, where we look for very explicit messages and send back associated responses. The former is less maintainable, as it requires changes whenever the calls to the Client are changed. It could also fall over in the future if we ever decide to make heavier use of `asyncio`, which would likely make the order of calls less deterministic.

**Comment by evalott100** [comment]
Merged i PR I forgot to reference
